# --- Configuración de Steam Toggle ---

# ¿Usar versión Flatpak de Steam? (true/false)
USE_FLATPAK="false"

# ¿Usar Gamescope para Big Picture? (true/false)
USE_GAMESCOPE="true"
GAMESCOPE_ARGS=""

# Comando para reabrir Steam normal cuando se cierre Big Picture (dejar vacío para no reabrir)
REOPEN_NORMAL_CMD=""

# --- Comandos Extra (Pantallas, Audio, etc.) ---

# Comando extra que se ejecuta al iniciar Big Picture
# Ejemplo: EXTRA_START_CMD="hyprctl keyword monitor DP-1,disable"
EXTRA_START_CMD="dms ipc outputs setProfile BigPicture"

# Comando extra que se ejecuta al cerrarse Steam (para revertir)
# Ejemplo: EXTRA_STOP_CMD="hyprctl keyword monitor DP-1,1920x1080@60,0x0,1"
EXTRA_STOP_CMD="dms ipc outputs setProfile Main"
